# -*- coding: utf-8 -*-
"""TensorFlow

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jTuuGqALxQ7e92ZtC7q4Wsy5vj-m8qaa
"""

import tensorflow as tf

mnist=tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train,x_test=x_train/255.0,x_test/255.0

model=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='sigmoid'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

predictions=model(x_train[:1]).numpy()
predictions

loss_fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)



loss_fn(y_train[:1],predictions).numpy()

model.compile(optimizer='adam',loss=loss_fn,metrics=['accuracy'])

model.fit(x_train,y_train,epochs=50)

model.evaluate(x_test,y_test,verbose=2)

x_train[0]

from google.colab import files

uploaded = files.upload()

import zipfile

zip_file = list(uploaded.keys())[0]

with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall('/content/cats_dogs')

train_ds = create_dataset(train_paths, train_labels)
val_ds = create_dataset(val_paths, val_labels)

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), activation='relu',
                           input_shape=(180,180,3)),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)

import numpy as np
from tensorflow.keras.utils import load_img, img_to_array

img_path = "/content/cats_dogs/dogs_vs_cats_subset/test/26.jpg"

img = load_img(img_path, target_size=(180,180))
img_array = img_to_array(img) / 255.0
img_array = np.expand_dims(img_array, axis=0)

prediction = model.predict(img_array)

print("Probability:", prediction[0][0])

if prediction[0][0] >= 0.5:
    print("Dog 🐶")
else:
    print("Cat 🐱")

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')

plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')

plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

model.save('/content/cats_dogs_model.keras')



model = tf.keras.models.load_model('/content/cats_dogs_model.keras')

import os

test_folder = "/content/cats_dogs/dogs_vs_cats_subset/test"

for file in os.listdir(test_folder)[:10]:
    img_path = os.path.join(test_folder, file)

    img = load_img(img_path, target_size=(180,180))
    img_array = img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    pred = model.predict(img_array, verbose=0)[0][0]

    print(file, "→", "Dog" if pred >= 0.5 else "Cat",
          "| Probability:", round(float(pred), 3))

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 8))

for i, file in enumerate(os.listdir(test_folder)[:9]):
    img_path = os.path.join(test_folder, file)

    img = load_img(img_path, target_size=(180,180))
    img_array = img_to_array(img) / 255.0

    pred = model.predict(
        np.expand_dims(img_array, axis=0),
        verbose=0
    )[0][0]

    label = "Dog" if pred >= 0.5 else "Cat"

    plt.subplot(3, 3, i+1)
    plt.imshow(img)
    plt.title(f"{label} ({pred:.2f})")
    plt.axis("off")

plt.tight_layout()
plt.show()

model.save("/content/cats_dogs_model.keras")

import os

print(os.path.exists("/content/cats_dogs_model.keras"))

import os

print(os.path.exists("/content/cats_dogs_model.keras"))

loss, accuracy = model.evaluate(val_ds)

print("Validation Accuracy:", accuracy)
print("Validation Loss:", loss)

import numpy as np

y_true = []
y_pred = []

for images, labels in val_ds:
    predictions = model.predict(images, verbose=0)

    y_true.extend(labels.numpy())
    y_pred.extend((predictions >= 0.5).astype(int).flatten())

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_true, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Cat", "Dog"]
)

disp.plot()
plt.show()

from sklearn.metrics import classification_report

print(classification_report(
    y_true,
    y_pred,
    target_names=["Cat", "Dog"]
))

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.1),
    tf.keras.layers.RandomZoom(0.1)
])

model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(180,180,3)),

    data_augmentation,

    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Conv2D(128, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.5),

    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=5
)

loss, accuracy = model.evaluate(val_ds)

print("Validation Accuracy:", accuracy)
print("Validation Loss:", loss)

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')

plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()
plt.show()

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')

plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()
plt.show()

model.save("/content/cats_dogs_model_augmented.keras")